"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { SCENARIOS } from "@/lib/scenarios";
import { loadProgress, type Progress } from "@/lib/progress";

function buildMarkdown(progress: Progress): string {
  const done = SCENARIOS.filter((s) => progress[s.id]);
  const lines: string[] = [
    "## FDE Practice Portfolio",
    "",
    "Hands-on forward-deployed-engineering simulations (graded by an AI senior-FDE reviewer on production-survivability, not demo polish):",
    "",
  ];
  for (const s of done) {
    const p = progress[s.id];
    lines.push(
      `- **${s.title}** (${s.customer} simulation) — best score ${p.bestScore}/100, ${p.attempts} attempt${p.attempts === 1 ? "" : "s"}.`,
      `  ${p.portfolioLine}`,
    );
  }
  lines.push("", "_Generated by FDE Sandbox._");
  return lines.join("\n");
}

export default function Portfolio() {
  const [progress, setProgress] = useState<Progress>({});
  const [copied, setCopied] = useState(false);
  useEffect(() => setProgress(loadProgress()), []);

  const done = SCENARIOS.filter((s) => progress[s.id]);
  const md = useMemo(() => buildMarkdown(progress), [progress]);

  async function copy() {
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  function download() {
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "fde-portfolio.md";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="text-3xl font-bold">Your portfolio</h1>
      <p className="mt-2 text-zinc-400">
        Your best result per engagement, as résumé-ready lines. Progress lives in
        this browser (no account needed).
      </p>

      {done.length === 0 ? (
        <div className="mt-10 rounded-xl border border-dashed border-zinc-700 bg-[var(--panel)] p-8 text-center">
          <p className="text-zinc-400">Nothing here yet.</p>
          <Link
            href="/sandbox"
            className="mt-4 inline-block rounded-lg bg-amber-400 px-5 py-3 font-semibold text-black transition hover:bg-amber-300"
          >
            Run your first engagement →
          </Link>
        </div>
      ) : (
        <>
          <div className="mt-8 space-y-4">
            {done.map((s) => {
              const p = progress[s.id];
              return (
                <div
                  key={s.id}
                  className="rounded-xl border border-zinc-800 bg-[var(--panel)] p-5"
                >
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <h2 className="font-semibold">{s.title}</h2>
                    <span className="mono rounded border border-zinc-700 bg-zinc-800/60 px-2 py-0.5 text-xs font-bold text-zinc-300">
                      best {p.bestScore}/100 · {p.attempts}{" "}
                      {p.attempts === 1 ? "attempt" : "attempts"}
                    </span>
                  </div>
                  <p className="mt-2 text-sm text-zinc-300">{p.portfolioLine}</p>
                </div>
              );
            })}
          </div>

          <div className="mt-8 rounded-xl border border-zinc-800 bg-[var(--panel)] p-5">
            <p className="mono text-xs uppercase tracking-widest text-zinc-500">
              export · markdown
            </p>
            <pre className="mono mt-3 overflow-x-auto whitespace-pre-wrap rounded-lg bg-[#0d1119] p-4 text-xs leading-relaxed text-zinc-300">
              {md}
            </pre>
            <div className="mt-4 flex gap-3">
              <button
                onClick={copy}
                className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-black transition hover:bg-amber-300"
              >
                {copied ? "Copied ✓" : "Copy markdown"}
              </button>
              <button
                onClick={download}
                className="rounded-lg border border-zinc-700 px-4 py-2 text-sm font-semibold text-zinc-200 transition hover:border-zinc-500"
              >
                Download .md
              </button>
            </div>
          </div>
        </>
      )}
    </main>
  );
}
