"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { SCENARIOS } from "@/lib/scenarios";
import { QUESTIONS } from "@/lib/interview";
import {
  clearAllProgress,
  loadInterviewProgress,
  loadProgress,
  type InterviewProgress,
  type Progress,
} from "@/lib/progress";

type Readiness = { tier: string; cls: string; blurb: string };

function readiness(shippedLevels: number, totalLevels: number, hireQs: number, totalQs: number): Readiness {
  const levelsDone = shippedLevels >= totalLevels;
  const interviewsStrong = hireQs >= Math.ceil(totalQs * 0.7);
  if (levelsDone && interviewsStrong)
    return {
      tier: "FDE INTERVIEW-READY",
      cls: "text-emerald-300 border-emerald-500/40 bg-emerald-500/10",
      blurb: "You've shipped every engagement and cleared the interview bar on most questions. Walk into the loop with reps, not nerves.",
    };
  if (shippedLevels >= 1 || hireQs >= 1)
    return {
      tier: "BUILDING THE CASE",
      cls: "text-amber-300 border-amber-500/40 bg-amber-500/10",
      blurb: "Good start. Ship the remaining engagements and push more interview answers to the hire bar to be loop-ready.",
    };
  return {
    tier: "WARMING UP",
    cls: "text-sky-300 border-sky-500/40 bg-sky-500/10",
    blurb: "You've attempted work but nothing has cleared the bar yet. Revise and resubmit — the reviewer rewards specificity.",
  };
}

function buildMarkdown(
  progress: Progress,
  interview: Record<string, InterviewProgress>,
): string {
  const done = SCENARIOS.filter((s) => progress[s.id]);
  const lines: string[] = [
    "## FDE Practice Portfolio",
    "",
    "Hands-on forward-deployed-engineering simulations (graded by an AI senior-FDE reviewer on production-survivability, not demo polish):",
    "",
  ];
  for (const s of done) {
    const p = progress[s.id];
    lines.push(
      `- **${s.title}** (${s.customer} simulation) — best score ${p.bestScore}/100, ${p.attempts} attempt${p.attempts === 1 ? "" : "s"}.`,
      `  ${p.portfolioLine}`,
    );
  }
  const drilled = QUESTIONS.filter((q) => interview[q.id]);
  if (drilled.length) {
    const passed = drilled.filter((q) =>
      ["hire", "strong_hire"].includes(interview[q.id].bestVerdict),
    );
    lines.push(
      "",
      `Mock-interview drills (calibrated against a frontier-lab FDE hiring bar): ${passed.length}/${drilled.length} questions at hire-or-above.`,
    );
    for (const q of drilled) {
      const p = interview[q.id];
      lines.push(
        `- ${q.category} — “${q.question.slice(0, 80)}${q.question.length > 80 ? "…" : ""}” → best: ${p.bestVerdict.replace(/_/g, " ")} (${p.bestScore}/100)`,
      );
    }
  }
  lines.push("", "_Generated by FDE Sandbox._");
  return lines.join("\n");
}

export default function Portfolio() {
  const [progress, setProgress] = useState<Progress>({});
  const [interview, setInterview] = useState<Record<string, InterviewProgress>>({});
  const [copied, setCopied] = useState(false);
  const [confirmReset, setConfirmReset] = useState(false);
  useEffect(() => {
    setProgress(loadProgress());
    setInterview(loadInterviewProgress());
  }, []);

  const done = SCENARIOS.filter((s) => progress[s.id]);
  const drilled = QUESTIONS.filter((q) => interview[q.id]);
  const md = useMemo(() => buildMarkdown(progress, interview), [progress, interview]);

  async function copy() {
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  function download() {
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "fde-portfolio.md";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="text-3xl font-bold">Your portfolio</h1>
      <p className="mt-2 text-zinc-400">
        Your best result per engagement, as résumé-ready lines. Progress lives in
        this browser (no account needed).
      </p>

      {done.length === 0 && drilled.length === 0 ? (
        <div className="mt-10 rounded-xl border border-dashed border-zinc-700 bg-[var(--panel)] p-8 text-center">
          <p className="text-zinc-400">Nothing here yet.</p>
          <Link
            href="/sandbox"
            className="mt-4 inline-block rounded-lg bg-amber-400 px-5 py-3 font-semibold text-black transition hover:bg-amber-300"
          >
            Run your first engagement →
          </Link>
        </div>
      ) : (
        <>
          {(() => {
            const shippedLevels = done.filter((s) => progress[s.id].verdict === "shipped").length;
            const hireQs = drilled.filter((q) =>
              ["hire", "strong_hire"].includes(interview[q.id].bestVerdict),
            ).length;
            const r = readiness(shippedLevels, SCENARIOS.length, hireQs, QUESTIONS.length);
            return (
              <div className="mt-8 rounded-xl border border-zinc-700 bg-[var(--panel)] p-6">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <p className="mono text-xs uppercase tracking-widest text-zinc-500">
                    your standing
                  </p>
                  <span className={`mono rounded-lg border px-4 py-2 text-sm font-bold ${r.cls}`}>
                    {r.tier}
                  </span>
                </div>
                <div className="mt-4 flex flex-wrap gap-3 text-sm">
                  <span className="mono rounded-lg border border-zinc-800 bg-[#0d1119] px-3 py-1.5 text-zinc-300">
                    {shippedLevels}/{SCENARIOS.length} engagements shipped
                  </span>
                  <span className="mono rounded-lg border border-zinc-800 bg-[#0d1119] px-3 py-1.5 text-zinc-300">
                    {hireQs}/{QUESTIONS.length} interviews at hire bar
                  </span>
                </div>
                <p className="mt-4 text-sm text-zinc-400">{r.blurb}</p>
              </div>
            );
          })()}

          <div className="mt-8 space-y-4">
            {done.map((s) => {
              const p = progress[s.id];
              return (
                <div
                  key={s.id}
                  className="rounded-xl border border-zinc-800 bg-[var(--panel)] p-5"
                >
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <h2 className="font-semibold">{s.title}</h2>
                    <span className="mono rounded border border-zinc-700 bg-zinc-800/60 px-2 py-0.5 text-xs font-bold text-zinc-300">
                      best {p.bestScore}/100 · {p.attempts}{" "}
                      {p.attempts === 1 ? "attempt" : "attempts"}
                    </span>
                  </div>
                  <p className="mt-2 text-sm text-zinc-300">{p.portfolioLine}</p>
                </div>
              );
            })}
          </div>

          {drilled.length > 0 && (
            <div className="mt-8">
              <h2 className="text-lg font-semibold">Interview drills</h2>
              <div className="mt-3 space-y-2">
                {drilled.map((q) => {
                  const p = interview[q.id];
                  const hireBar = ["hire", "strong_hire"].includes(p.bestVerdict);
                  return (
                    <div
                      key={q.id}
                      className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-zinc-800 bg-[var(--panel)] px-4 py-3"
                    >
                      <p className="text-sm text-zinc-300">
                        <span className="mono text-xs uppercase text-zinc-500">
                          {q.category} ·{" "}
                        </span>
                        {q.question.slice(0, 70)}
                        {q.question.length > 70 ? "…" : ""}
                      </p>
                      <span
                        className={`mono rounded border px-2 py-0.5 text-[10px] font-bold uppercase ${
                          hireBar
                            ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-400"
                            : "border-amber-500/40 bg-amber-500/10 text-amber-400"
                        }`}
                      >
                        {p.bestVerdict.replace(/_/g, " ")} · {p.bestScore}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          <div className="mt-8 rounded-xl border border-zinc-800 bg-[var(--panel)] p-5">
            <p className="mono text-xs uppercase tracking-widest text-zinc-500">
              export · markdown
            </p>
            <pre className="mono mt-3 overflow-x-auto whitespace-pre-wrap rounded-lg bg-[#0d1119] p-4 text-xs leading-relaxed text-zinc-300">
              {md}
            </pre>
            <div className="mt-4 flex gap-3">
              <button
                onClick={copy}
                className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-black transition hover:bg-amber-300"
              >
                {copied ? "Copied ✓" : "Copy markdown"}
              </button>
              <button
                onClick={download}
                className="rounded-lg border border-zinc-700 px-4 py-2 text-sm font-semibold text-zinc-200 transition hover:border-zinc-500"
              >
                Download .md
              </button>
            </div>
          </div>

          <div className="mt-6 flex items-center justify-between gap-3">
            <p className="text-xs text-zinc-600">
              Progress is stored only in this browser.
            </p>
            {confirmReset ? (
              <span className="flex items-center gap-2 text-xs">
                <span className="text-zinc-400">Erase all progress?</span>
                <button
                  onClick={() => {
                    clearAllProgress();
                    setProgress({});
                    setInterview({});
                    setConfirmReset(false);
                  }}
                  className="rounded border border-rose-500/40 bg-rose-500/10 px-2 py-1 font-semibold text-rose-300"
                >
                  Yes, reset
                </button>
                <button
                  onClick={() => setConfirmReset(false)}
                  className="rounded border border-zinc-700 px-2 py-1 text-zinc-400"
                >
                  Cancel
                </button>
              </span>
            ) : (
              <button
                onClick={() => setConfirmReset(true)}
                className="text-xs text-zinc-500 underline-offset-2 hover:text-rose-400 hover:underline"
              >
                Reset progress
              </button>
            )}
          </div>
        </>
      )}
    </main>
  );
}
